#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $USER_USERNAME;
	CREATE DATABASE $USER_DB_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $USER_DB_NAME TO $USER_USERNAME;
    ALTER USER $USER_USERNAME WITH PASSWORD '$USER_PASSWORD';
EOSQL