version: '3.8'

x-database: &postgres
  environment: &postgres-environment
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_DB: ${POSTGRES_DATABASE_NAME}
    POSTGRES_PORT: ${POSTGRES_PORT}
    POSTGRES_HOST: ${POSTGRES_IP}

services:
  # DATABASE SERVICE
  postgres:
    <<: *postgres
    image: postgres
    container_name: recipe_heaven_db
    restart: unless-stopped
    networks:
      backend:
        ipv4_address: ${POSTGRES_IP}
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data


  # MAILING APPLICATION
  mail:
    container_name: recipe_heaven_mail
    restart: unless-stopped
    image: namshi/smtp
    networks:
      - backend

  # APPLICATION SERVER: API
  server:
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: no.twct.recipeheaven/appserver
    container_name: recipe_heaven_server
    restart: unless-stopped
    environment:
      <<: *postgres-environment
      APPSERVER_PORT: ${APPSERVER_PORT}
    networks:
      frontend:
      backend:
        ipv4_address: ${APPSERVER_IP}
    ports:
      - ${APPSERVER_PORT}:${APPSERVER_PORT}

    depends_on:
      - 'postgres'
    volumes:
      - type: volume
        source: app_images
        target: /images

# NETWORKS FOR ALL THE CONTAINERS
networks:
  backend:
    name: recipe_heaven_backend
    ipam:
      driver: default
      config:
        - subnet: 10.50.50.0/24

  frontend:
    name: recipe_heaven_frontend
    driver: bridge

# NAMED VOLUMES FOR PERSISTENT STORAGE
volumes:
  postgres:
  app_images:
  nginx_data:
