version: '3.1'

services:
  db:
    container_name: recipe_heaven_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: recipe-heaven
      POSTGRES_PASSWORD: example
    networks:
      - backend
    ports:
      - 5432:5432
  mail:
    container_name: recipe_heaven_mail
    restart: always
    image: namshi/smtp
    networks:
      - backend
  server:
    build: .
    container_name: recipe_heaven
    image: no.twct.recipeheaven/appserver
    depends_on:
      - 'db'
    networks:
      - backend
    volumes:
      - ./target:/config/dropins
    ports:
      - 9080:9080
networks:
  backend:
    driver: bridge

